services:
  api-devleopment:
    container_name: harmonize-fastapi-dev
    build: .
    ports:
      - "8000:8000"
    command: /harmonize/.venv/bin/fastapi dev main.py --host 0.0.0.0 --port 8000
    develop:
      watch:
        - action: sync
          path: ./harmonize
          target: /harmonize/
          # Exclude the project virtual environment
          ignore:
            - .venv/
        - action: rebuild
          path: ./harmonize/pyproject.toml
    profiles:
      - "dev"
  api:
    container_name: harmonize-fastapi
    build: .
    ports:
      - "8000:8000"
    command: /harmonize/.venv/bin/fastapi run main.py --host 0.0.0.0 --port 8000
    profiles:
      - "prod"
